apiVersion: v1
kind: Service
metadata:
  name: cm
  labels:
    name: cm
spec:
   type: LoadBalancer
   ports:
    - port: 8181
      targetPort: 8181
   selector:
     name: cm
     version: "1.0.0-x"
