apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
#  namespace: argocd

  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  project: default

  source:
      repoURL: https://github.com/dimon99/prometeus-plugin-go.git
      targetRevision: HEAD
      path: greenblue/

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
