apiVersion: v1
kind: Service
metadata:
  name: custom-metric
  labels:
    name: custom-metric
  namespace: default
spec:
   type: LoadBalancer
   ports:
    - port: 80
      targetPort: 8181
   selector:
        name: custom-metric
        color: blue
