apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metric-green
  labels:
     name: green
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      name: custom-metric
  template:
    metadata:
      labels:
         name: custom-metric
         color: green
    spec:
      containers:
      - name: custom-metric
        image: dfedoruk/custom-metric:1.0.0
        ports:
        - containerPort: 8181
      imagePullSecrets:
      - name: myregistrykey