apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metric
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: custom-metric
  template:
    metadata:
      labels:
         app: custom-metric
    spec:
      containers:
      - name: custom-metric
        image: dfedoruk/custom-metric:v1.1.226
        ports:
        - containerPort: 8181
